.vscode/ticket.code-snippets

Changed Snippets

---

.vscode/settings.json
content/04kapitel.tex

Skios xx backlog lukas

---

content/04kapitel.tex

SKIOS-120-Deplyoemt-Readme

---

CHANGELOG.md
content/04kapitel.tex

SKIOS-133 - SKIOS-133-orm-readme

---

bibliographie.bib
content/04kapitel.tex

Skios xx backlog tim

---

CHANGELOG.md
content/04kapitel.tex

SKIOS-137-Angular-Service-Framework

---

content/04kapitel.tex

Skios 84 initial uniform polling implementation

---

content/04kapitel.tex

Added Story for SKIOS-119-frontend-readme

---

content/04kapitel.tex

Added Stories for SKIOS 121 and SKIOS 115

---

content/04kapitel.tex

added user-story for SKIOS-117.

---

content/04kapitel.tex

Doku to SKIOS-109-backend-feed-mutations

---

content/04kapitel.tex

SKIOS-XX-documentation-simon-morgenstern

---

.github/CODEOWNERS
ads/acronyms.tex
ads/header.tex
bibliographie.bib
content/04kapitel.tex
content/05kapitel.tex

Skios 122 la te x architecture overview

---

content/04kapitel.tex

SKIOS-80-article-view-page

---

content/04kapitel.tex

SKIOS-82-feed-overview-page

---

content/04kapitel.tex

SKIOS-145-mutators-and-resolvers-for-bookmarks

---

content/04kapitel.tex

Added story

---

content/01kapitel.tex
content/04kapitel.tex
content/05kapitel.tex

Skios 166 la te x technical changelog

---

content/04kapitel.tex

SKIOS-147-angular-bookmarks-page

---

content/02kapitel.tex
content/04kapitel.tex

SKIOS 164 added meeting summary.

---

content/04kapitel.tex

my user stories

---

content/04kapitel.tex

Skios 125 la te x article and feed workflow explanation and sequence diagrams - user Story documentation

---

content/06kapitel.tex

Text erstellt version 1.0

---

content/04kapitel.tex

Added Documentation

---

content/03kapitel.tex
content/04kapitel.tex
content/06kapitel.tex

- [] PRE-MERGE add tag to start drone automation

added sprint summary
